import { Book, Country } from 'interfaces';

export const BOOKS_ON_SALE: Book[] = [
  {
    title: 'Greatest Works of Oscar Wilde',
    author: 'Oscar Wilde',
    price: 42.43,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81Ko4PmfouS.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81pTUrv0QnL.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/911vRWx1WPL.jpg',
    ],
    rating: 4.6,
  },
  {
    title: 'The Complete Novels of Sherlock Holmes',
    author: 'Arthur Conan Doyle',
    price: 54.55,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81StezluKUS.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/914eICOJ5NL.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/814RZZuiU6L.jpg',
    ],
    rating: 4.5,
  },
  {
    title: '1984',
    author: 'George Orwell',
    price: 249.99,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81vHA1+GmhS.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81nLM3CiOHL.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/91THPuJTLyL.jpg',
    ],
    rating: 5,
  },
  {
    title: 'Robinson Crusoe',
    author: 'Daniel Defoe',
    price: 36.25,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81cp-sm9FzS.jpg',
      'https://m.media-amazon.com/images/I/81qcRZzW-xS.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81FX-yUxY8S.jpg',
    ],
    rating: 4.4,
  },
  {
    title: 'The Adventures of Tom Sawyer',
    author: 'Mark Twain',
    price: 48.99,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81KTDij0XyS.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/810c9q8YfmS.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81PWcHXCcHS.jpg',
    ],
    rating: 4.73,
  },
  {
    title: 'The Adventures of Huckleberry Finn',
    author: 'Mark Twain',
    price: 51.17,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/811euwWZ+dS.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81wXusqXhaS.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81bAG-NiWwS.jpg',
    ],
    rating: 4.68,
  },
  {
    title: 'The Merry Adventures Of Robin Hood',
    author: 'Howard Pyle',
    price: 69.65,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81p7i7vJiGS.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/916vgKv6mES.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81M9LWEuX0S.jpg',
    ],
    rating: 4.3,
  },
  {
    title: 'Just So Stories',
    author: 'Rudyard Kipling',
    price: 64.25,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81xh95E0spL.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/716f2PqpnfL.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81cNDVLex+L.jpg',
    ],
    rating: 4.4,
  },
  {
    title: 'Gullivers Travels',
    author: 'Jonathan Swift',
    price: 199.99,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81OGJ-a3xCS.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/814vO0KuDlS.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81jAOE4CvIS.jpg',
    ],
    rating: 4.4,
  },
  {
    title: '1984',
    author: 'George Orwell',
    price: 99.99,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81fcLJo+FNL.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81Jqipul+aL.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81CKcgmg9ZL.jpg',
    ],
    rating: 5,
  },
  {
    title: 'Animal Farm',
    author: 'George Orwell',
    price: 79,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/71WI1r5j6HS.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/91X38lJwhuL.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/710LnjoVRSS.jpg',
    ],
    rating: 5,
  },
  {
    title: 'The Picture of Dorian Gray',
    author: 'Oscar Wilde',
    price: 172,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81opmtlMQ5L.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81UMlcJ++fL.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81SlZyTw3DL.jpg',
    ],
    rating: 4.7,
  },
  {
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    price: 85,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/71sJRMkeBNS.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81KHq5cLaGL.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/71wU4OOlDoL.jpg',
    ],
    rating: 4.4,
  },
  {
    title: 'The Greatest Short Stories of Leo Tolstoy',
    author: 'Leo Tolstoy',
    price: 169,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/819M94xydSL.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81S-ubePUPL.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81wYYHrsgDL.jpg',
    ],
    rating: 4.5,
  },
  {
    title: 'War and Peace',
    author: 'Leo Tolstoy',
    price: 299.99,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81KPzmVf2mL.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/817OvUX5pCL.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81g814qRGzL.jpg',
    ],
    rating: 4.2,
  },
  {
    title: 'Treasure Island',
    author: 'Robert Louis Stevenson',
    price: 70.23,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/819gepUWtdS.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81KEIFn8oIS.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81B3lJa0fJS.jpg',
    ],
    rating: 5,
  },
  {
    title: 'Crime and Punishment',
    author: 'Fyodor Dostoevsky',
    price: 183,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81vTpOYpwOL.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/71DRqUnf+VL.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/91GblDf7AAL.jpg',
    ],
    rating: 4.5,
  },
  {
    title: 'The Greatest Works of George Orwell',
    author: 'George Orwell',
    price: 99.99,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81ZP6UV-y1S.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81qrl4UcFZS.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81cFo-zUgGS.jpg',
    ],
    rating: 4.7,
  },
  {
    title: 'The Lost World',
    author: 'Arthur Conan Doyle',
    price: 89.02,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/916RXLP7bFL.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81QgpbbeApL.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81FdNslpmyL.jpg',
    ],
    rating: 4.7,
  },
  {
    title: 'The Little Prince',
    author: 'Antoine De Saint-Exupery',
    price: 159,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/91AWwH8U3HS.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/818rTgnmlEL.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81gH1PxsPeL.jpg',
    ],
    rating: 5,
  },
  {
    title: 'The Prince and the Pauper',
    author: 'Mark Twain',
    price: 82.5,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81XdTyHW0YL.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/71Ozwu5ygVL.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/61hGgShdE7L.jpg',
    ],
    rating: 4.4,
  },
  {
    title: 'The Jungle Book',
    author: 'Rudyard Kipling',
    price: 69,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81HPv6PnpCS.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81ABgNA0CUS.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81OztKEF2JS.jpg',
    ],
    rating: 4.3,
  },
  {
    title: 'The Greatest Novels of Mark Twain',
    author: 'Mark Twain',
    price: 299,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/814Ynk2xy8S.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81m+TpdTZPL.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81Z4QNDkvEL.jpg',
    ],
    rating: 4.6,
  },
  {
    title: 'Macbeth',
    author: 'William Shakespeare',
    price: 106,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/71JLzfjq57S.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/71vKRps2huL.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/71viaoPUU-L.jpg',
    ],
    rating: 4.3,
  },
  {
    title: 'The Three Musketeers',
    author: 'Alexandre Dumas',
    price: 109,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/71BzSTXtH7L.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/714SClI2neL.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/61ZOUhUqMRL.jpg',
    ],
    rating: 4.7,
  },
  {
    title: 'Oliver Twist',
    author: 'Charles Dickens',
    price: 59,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81X9mpk-mwS.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/91nIxYbBx6L.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81mgaAKfAbL.jpg',
    ],
    rating: 4.4,
  },
  {
    title: 'The Complete Novels of Sherlock Holmes',
    author: 'Arthur Conan Doyle',
    price: 205,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81KDmsPWVlS.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/912govRG21L.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81AufUYBZcL.jpg',
    ],
    rating: 4.7,
  },
  {
    title: 'Hamlet',
    author: 'William Shakespeare',
    price: 94,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/61ewyOG0IZS.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/71kwoQfDz7S.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/71jWRNqXd3S.jpg',
    ],
    rating: 4.2,
  },
  {
    title: '20,000 Leagues Under the Sea',
    author: 'Jules Verne',
    price: 149,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81OaNTm8peS.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/71miP3vpXjS.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81NBZy56u3S.jpg',
    ],
    rating: 4.8,
  },
  {
    title: 'Wuthering Heights',
    author: 'Emily Bronte',
    price: 97.99,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81+x6eHkSdS.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/91rYn7jTFxL.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/819iBo+totL.jpg',
    ],
    rating: 4.3,
  },
  {
    title: 'Greatest Comedies of Shakespeare',
    author: 'William Shakespeare',
    price: 189,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/91iXOsD4itS.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81LSekLjNTL.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/91Uc6oOBeqL.jpg',
    ],
    rating: 4.5,
  },
  {
    title: 'Greatest Tragedies of Shakespeare',
    author: 'William Shakespeare',
    price: 179.09,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/91cyxhmf4cS.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/718GKfxfNgL.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/91bC0iTUHEL.jpg',
    ],
    rating: 4.6,
  },
  {
    title: 'Journey to the Centre of the Earth',
    author: 'Jules Verne',
    price: 93.99,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/8127crrQWJL.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81tcV0eLhGS.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81TZFrGgL+S.jpg',
    ],
    rating: 4.4,
  },
  {
    title: 'The Jungle Book',
    author: 'Rudyard Kipling',
    price: 79,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/71nhAMK6xES.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81oFlbGiIDL.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/718NaMLJfJL.jpg',
    ],
    rating: 4.8,
  },
  {
    title: 'The Call Of The Wild',
    author: 'Jack London',
    price: 100,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/61p+TVZG19S.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81E5fuqQJ9L.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/71xGPtTtMEL.jpg',
    ],
    rating: 4.3,
  },
  {
    title: 'The Importance of Being Earnest',
    author: 'Oscar Wilde',
    price: 75,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/71RZBszBLkS.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81ptGGnjNkS.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/71MidUeFyHS.jpg',
    ],
    rating: 4.3,
  },
  {
    title: 'The Greatest Short Stories of Anton Chekhov',
    author: 'Anton Chekhov',
    price: 97,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81-Y2qizxxS.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/810dJH8qgrS.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81AbrNAnXZS.jpg',
    ],
    rating: 4.3,
  },
  {
    title: 'Great Expectations',
    author: 'Charles Dickens',
    price: 249.99,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/814S3F7UB9S.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81LXPqobHpL.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81YIvhoiukL.jpg',
    ],
    rating: 4.7,
  },
  {
    title: 'Gone with the Wind',
    author: 'Margaret Mitchell',
    price: 189,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/819bFn9OHDS.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81DLWJXDjPL.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/91ePRG0ZNIL.jpg',
    ],
    rating: 5,
  },
  {
    title: "The Complete Grimms' Fairy Tales",
    author: 'Jacob Grimm & Wilhelm Grimm',
    price: 109,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81zr7PyHa5S.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/91f5YEimu3S.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81ubTFD9C6S.jpg',
    ],
    rating: 4.8,
  },
  {
    title: "The Complete Grimms' Fairy Tales",
    author: 'Jacob Grimm & Wilhelm Grimm',
    price: 249.95,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/91xEPAl95+S.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81w-kpPXL8L.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81-79iqDrxL.jpg',
    ],
    rating: 4.6,
  },
  {
    title: 'The Case-Book of Sherlock Holmes',
    author: 'Arthur Conan Doyle',
    price: 115.99,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81iXNr+yx2S.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/71MFta6USDS.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81c+e7TgwDS.jpg',
    ],
    rating: 4.4,
  },
  {
    title: 'The Adventures of Sherlock Holmes',
    author: 'Arthur Conan Doyle',
    price: 158.73,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/71UrjLQcJSS.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81O2RoH0s3S.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/71299eCnhtS.jpg',
    ],
    rating: 4.5,
  },
  {
    title: 'The Count of Monte Cristo',
    author: 'Alexandre Dumas',
    price: 139,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/816KABRp8-S.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81ZG-FuqZlS.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/71po24rSRIS.jpg',
    ],
    rating: 4.5,
  },
  {
    title: 'The Man In The Iron Mask',
    author: 'Alexandre Dumas',
    price: 139.75,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/716NIXc-mCL.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81mASkt2m1L.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/714zTGg0ghL.jpg',
    ],
    rating: 4.3,
  },
  {
    title: 'The Beautiful and Damned',
    author: 'F. Scott Fitzgerald',
    price: 104.75,
    urlToImages: [
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/91gO+dKxJWS.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81QzjqKMP-S.jpg',
      'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/718WGz1kzJS.jpg',
    ],
    rating: 4.4,
  },
];

export const COUNTRY: Country[] = [
  { name: '', code: 'X' },
  { name: 'Afghanistan', code: 'AF' },
  { name: 'Åland Islands', code: 'AX' },
  { name: 'Albania', code: 'AL' },
  { name: 'Algeria', code: 'DZ' },
  { name: 'American Samoa', code: 'AS' },
  { name: 'AndorrA', code: 'AD' },
  { name: 'Angola', code: 'AO' },
  { name: 'Anguilla', code: 'AI' },
  { name: 'Antarctica', code: 'AQ' },
  { name: 'Antigua and Barbuda', code: 'AG' },
  { name: 'Argentina', code: 'AR' },
  { name: 'Armenia', code: 'AM' },
  { name: 'Aruba', code: 'AW' },
  { name: 'Australia', code: 'AU' },
  { name: 'Austria', code: 'AT' },
  { name: 'Azerbaijan', code: 'AZ' },
  { name: 'Bahamas', code: 'BS' },
  { name: 'Bahrain', code: 'BH' },
  { name: 'Bangladesh', code: 'BD' },
  { name: 'Barbados', code: 'BB' },
  { name: 'Belarus', code: 'BY' },
  { name: 'Belgium', code: 'BE' },
  { name: 'Belize', code: 'BZ' },
  { name: 'Benin', code: 'BJ' },
  { name: 'Bermuda', code: 'BM' },
  { name: 'Bhutan', code: 'BT' },
  { name: 'Bolivia', code: 'BO' },
  { name: 'Bosnia and Herzegovina', code: 'BA' },
  { name: 'Botswana', code: 'BW' },
  { name: 'Bouvet Island', code: 'BV' },
  { name: 'Brazil', code: 'BR' },
  { name: 'British Indian Ocean Territory', code: 'IO' },
  { name: 'Brunei Darussalam', code: 'BN' },
  { name: 'Bulgaria', code: 'BG' },
  { name: 'Burkina Faso', code: 'BF' },
  { name: 'Burundi', code: 'BI' },
  { name: 'Cambodia', code: 'KH' },
  { name: 'Cameroon', code: 'CM' },
  { name: 'Canada', code: 'CA' },
  { name: 'Cape Verde', code: 'CV' },
  { name: 'Cayman Islands', code: 'KY' },
  { name: 'Central African Republic', code: 'CF' },
  { name: 'Chad', code: 'TD' },
  { name: 'Chile', code: 'CL' },
  { name: 'China', code: 'CN' },
  { name: 'Christmas Island', code: 'CX' },
  { name: 'Cocos (Keeling) Islands', code: 'CC' },
  { name: 'Colombia', code: 'CO' },
  { name: 'Comoros', code: 'KM' },
  { name: 'Congo', code: 'CG' },
  { name: 'Congo, The Democratic Republic of the', code: 'CD' },
  { name: 'Cook Islands', code: 'CK' },
  { name: 'Costa Rica', code: 'CR' },
  { name: "Cote D'Ivoire", code: 'CI' },
  { name: 'Croatia', code: 'HR' },
  { name: 'Cuba', code: 'CU' },
  { name: 'Cyprus', code: 'CY' },
  { name: 'Czech Republic', code: 'CZ' },
  { name: 'Denmark', code: 'DK' },
  { name: 'Djibouti', code: 'DJ' },
  { name: 'Dominica', code: 'DM' },
  { name: 'Dominican Republic', code: 'DO' },
  { name: 'Ecuador', code: 'EC' },
  { name: 'Egypt', code: 'EG' },
  { name: 'El Salvador', code: 'SV' },
  { name: 'Equatorial Guinea', code: 'GQ' },
  { name: 'Eritrea', code: 'ER' },
  { name: 'Estonia', code: 'EE' },
  { name: 'Ethiopia', code: 'ET' },
  { name: 'Falkland Islands (Malvinas)', code: 'FK' },
  { name: 'Faroe Islands', code: 'FO' },
  { name: 'Fiji', code: 'FJ' },
  { name: 'Finland', code: 'FI' },
  { name: 'France', code: 'FR' },
  { name: 'French Guiana', code: 'GF' },
  { name: 'French Polynesia', code: 'PF' },
  { name: 'French Southern Territories', code: 'TF' },
  { name: 'Gabon', code: 'GA' },
  { name: 'Gambia', code: 'GM' },
  { name: 'Georgia', code: 'GE' },
  { name: 'Germany', code: 'DE' },
  { name: 'Ghana', code: 'GH' },
  { name: 'Gibraltar', code: 'GI' },
  { name: 'Greece', code: 'GR' },
  { name: 'Greenland', code: 'GL' },
  { name: 'Grenada', code: 'GD' },
  { name: 'Guadeloupe', code: 'GP' },
  { name: 'Guam', code: 'GU' },
  { name: 'Guatemala', code: 'GT' },
  { name: 'Guernsey', code: 'GG' },
  { name: 'Guinea', code: 'GN' },
  { name: 'Guinea-Bissau', code: 'GW' },
  { name: 'Guyana', code: 'GY' },
  { name: 'Haiti', code: 'HT' },
  { name: 'Heard Island and Mcdonald Islands', code: 'HM' },
  { name: 'Holy See (Vatican City State)', code: 'VA' },
  { name: 'Honduras', code: 'HN' },
  { name: 'Hong Kong', code: 'HK' },
  { name: 'Hungary', code: 'HU' },
  { name: 'Iceland', code: 'IS' },
  { name: 'India', code: 'IN' },
  { name: 'Indonesia', code: 'ID' },
  { name: 'Iran, Islamic Republic Of', code: 'IR' },
  { name: 'Iraq', code: 'IQ' },
  { name: 'Ireland', code: 'IE' },
  { name: 'Isle of Man', code: 'IM' },
  { name: 'Israel', code: 'IL' },
  { name: 'Italy', code: 'IT' },
  { name: 'Jamaica', code: 'JM' },
  { name: 'Japan', code: 'JP' },
  { name: 'Jersey', code: 'JE' },
  { name: 'Jordan', code: 'JO' },
  { name: 'Kazakhstan', code: 'KZ' },
  { name: 'Kenya', code: 'KE' },
  { name: 'Kiribati', code: 'KI' },
  { name: "Korea, Democratic People'S Republic of", code: 'KP' },
  { name: 'Korea, Republic of', code: 'KR' },
  { name: 'Kuwait', code: 'KW' },
  { name: 'Kyrgyzstan', code: 'KG' },
  { name: "Lao People'S Democratic Republic", code: 'LA' },
  { name: 'Latvia', code: 'LV' },
  { name: 'Lebanon', code: 'LB' },
  { name: 'Lesotho', code: 'LS' },
  { name: 'Liberia', code: 'LR' },
  { name: 'Libyan Arab Jamahiriya', code: 'LY' },
  { name: 'Liechtenstein', code: 'LI' },
  { name: 'Lithuania', code: 'LT' },
  { name: 'Luxembourg', code: 'LU' },
  { name: 'Macao', code: 'MO' },
  { name: 'Macedonia, The Former Yugoslav Republic of', code: 'MK' },
  { name: 'Madagascar', code: 'MG' },
  { name: 'Malawi', code: 'MW' },
  { name: 'Malaysia', code: 'MY' },
  { name: 'Maldives', code: 'MV' },
  { name: 'Mali', code: 'ML' },
  { name: 'Malta', code: 'MT' },
  { name: 'Marshall Islands', code: 'MH' },
  { name: 'Martinique', code: 'MQ' },
  { name: 'Mauritania', code: 'MR' },
  { name: 'Mauritius', code: 'MU' },
  { name: 'Mayotte', code: 'YT' },
  { name: 'Mexico', code: 'MX' },
  { name: 'Micronesia, Federated States of', code: 'FM' },
  { name: 'Moldova, Republic of', code: 'MD' },
  { name: 'Monaco', code: 'MC' },
  { name: 'Mongolia', code: 'MN' },
  { name: 'Montserrat', code: 'MS' },
  { name: 'Morocco', code: 'MA' },
  { name: 'Mozambique', code: 'MZ' },
  { name: 'Myanmar', code: 'MM' },
  { name: 'Namibia', code: 'NA' },
  { name: 'Nauru', code: 'NR' },
  { name: 'Nepal', code: 'NP' },
  { name: 'Netherlands', code: 'NL' },
  { name: 'Netherlands Antilles', code: 'AN' },
  { name: 'New Caledonia', code: 'NC' },
  { name: 'New Zealand', code: 'NZ' },
  { name: 'Nicaragua', code: 'NI' },
  { name: 'Niger', code: 'NE' },
  { name: 'Nigeria', code: 'NG' },
  { name: 'Niue', code: 'NU' },
  { name: 'Norfolk Island', code: 'NF' },
  { name: 'Northern Mariana Islands', code: 'MP' },
  { name: 'Norway', code: 'NO' },
  { name: 'Oman', code: 'OM' },
  { name: 'Pakistan', code: 'PK' },
  { name: 'Palau', code: 'PW' },
  { name: 'Palestinian Territory, Occupied', code: 'PS' },
  { name: 'Panama', code: 'PA' },
  { name: 'Papua New Guinea', code: 'PG' },
  { name: 'Paraguay', code: 'PY' },
  { name: 'Peru', code: 'PE' },
  { name: 'Philippines', code: 'PH' },
  { name: 'Pitcairn', code: 'PN' },
  { name: 'Poland', code: 'PL' },
  { name: 'Portugal', code: 'PT' },
  { name: 'Puerto Rico', code: 'PR' },
  { name: 'Qatar', code: 'QA' },
  { name: 'Reunion', code: 'RE' },
  { name: 'Romania', code: 'RO' },
  { name: 'Russian Federation', code: 'RU' },
  { name: 'RWANDA', code: 'RW' },
  { name: 'Saint Helena', code: 'SH' },
  { name: 'Saint Kitts and Nevis', code: 'KN' },
  { name: 'Saint Lucia', code: 'LC' },
  { name: 'Saint Pierre and Miquelon', code: 'PM' },
  { name: 'Saint Vincent and the Grenadines', code: 'VC' },
  { name: 'Samoa', code: 'WS' },
  { name: 'San Marino', code: 'SM' },
  { name: 'Sao Tome and Principe', code: 'ST' },
  { name: 'Saudi Arabia', code: 'SA' },
  { name: 'Senegal', code: 'SN' },
  { name: 'Serbia and Montenegro', code: 'CS' },
  { name: 'Seychelles', code: 'SC' },
  { name: 'Sierra Leone', code: 'SL' },
  { name: 'Singapore', code: 'SG' },
  { name: 'Slovakia', code: 'SK' },
  { name: 'Slovenia', code: 'SI' },
  { name: 'Solomon Islands', code: 'SB' },
  { name: 'Somalia', code: 'SO' },
  { name: 'South Africa', code: 'ZA' },
  { name: 'South Georgia and the South Sandwich Islands', code: 'GS' },
  { name: 'Spain', code: 'ES' },
  { name: 'Sri Lanka', code: 'LK' },
  { name: 'Sudan', code: 'SD' },
  { name: 'Suriname', code: 'SR' },
  { name: 'Svalbard and Jan Mayen', code: 'SJ' },
  { name: 'Swaziland', code: 'SZ' },
  { name: 'Sweden', code: 'SE' },
  { name: 'Switzerland', code: 'CH' },
  { name: 'Syrian Arab Republic', code: 'SY' },
  { name: 'Taiwan, Province of China', code: 'TW' },
  { name: 'Tajikistan', code: 'TJ' },
  { name: 'Tanzania, United Republic of', code: 'TZ' },
  { name: 'Thailand', code: 'TH' },
  { name: 'Timor-Leste', code: 'TL' },
  { name: 'Togo', code: 'TG' },
  { name: 'Tokelau', code: 'TK' },
  { name: 'Tonga', code: 'TO' },
  { name: 'Trinidad and Tobago', code: 'TT' },
  { name: 'Tunisia', code: 'TN' },
  { name: 'Turkey', code: 'TR' },
  { name: 'Turkmenistan', code: 'TM' },
  { name: 'Turks and Caicos Islands', code: 'TC' },
  { name: 'Tuvalu', code: 'TV' },
  { name: 'Uganda', code: 'UG' },
  { name: 'Ukraine', code: 'UA' },
  { name: 'United Arab Emirates', code: 'AE' },
  { name: 'United Kingdom', code: 'GB' },
  { name: 'United States', code: 'US' },
  { name: 'United States Minor Outlying Islands', code: 'UM' },
  { name: 'Uruguay', code: 'UY' },
  { name: 'Uzbekistan', code: 'UZ' },
  { name: 'Vanuatu', code: 'VU' },
  { name: 'Venezuela', code: 'VE' },
  { name: 'Viet Nam', code: 'VN' },
  { name: 'Virgin Islands, British', code: 'VG' },
  { name: 'Virgin Islands, U.S.', code: 'VI' },
  { name: 'Wallis and Futuna', code: 'WF' },
  { name: 'Western Sahara', code: 'EH' },
  { name: 'Yemen', code: 'YE' },
  { name: 'Zambia', code: 'ZM' },
  { name: 'Zimbabwe', code: 'ZW' },
];
